### ISSUE TITLE
Incorrect compiler warning checking

### ISSUE THREAD

**Issue by shao-hua-li** [DeadCodeProductions/diopter#37]
It seems that "=" is not a proper comparison here, instead, you should use something like
```
for line in result.stdout_stderr_output.splitlines():
                for each_warn in self.checked_warnings:
                    if each_warn in line:
                        return SanitizationResult(check_warnings_failed=True)
```
https://github.com/DeadCodeProductions/diopter/blob/3aa43069879a48f24164e2aa58aa7cc438fc7273/diopter/sanitizer.py#L230

**Comment by thetheodor** [comment]
Fixed by #39
