### ISSUE TITLE
Incorrect command line option

### ISSUE THREAD

**Issue by shao-hua-li** [DeadCodeProductions/diopter#59]
Do you mean "-Weverything" here as you use clang as the compiler.
https://github.com/DeadCodeProductions/diopter/blob/81591d4f0082fff2d1015eff7d4c6828d12adadd/diopter/sanitizer.py#L289

**Comment by thetheodor** [comment]
I guess `-Weverything` would enable more warnings, but at this particular place it doesn't really matter. As only the sanitizer result is used

**Comment by thetheodor** [comment]
Maybe it makes sense to add this for the warning's checks. But `-Wall` is definitely not incorrect
